# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e25d1537e1362d3638e7379d73989d78abe44c8c98b47b23191e35327fad15e66a159aee5d86afe8113d99d8c50c57508e28afd1d16a056fc62b8a5541dfb88

test:
  secret_key_base: 84114b0ae6121e996a1b6ce31142bdd774a5904cc1044cfdfe05428eab228b910fb7655fc970d928570e68dc58a0925893ff103fbe886ca57e4fe0ac56976063

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
